# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea9a20bbe373215c7b4ab602e5310a8053016ed88808e4469988b1177daba223b8e4f51d61baa6b8eee34796f52dc9f650e8fe973594640925c6dc2df1daf919

test:
  secret_key_base: 89f6634ee7147c6095397f1a7bb84e193fe41ca32d052cc98cfb9078b0ba52d68d03cd2228e149d375fb3fa1b908b4ae3828ddd72a6bdfce145185e7531b5383

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
